VIA_ENABLE = yes
LTO_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
GRAVE_ESC_ENABLE = yes
ENCODER_MAP_ENABLE = no

WPM_ENABLE = no
